"""
Broker base interface for all adapters.
Use apenas APIs oficiais. Este módulo define o contrato que os adapters devem seguir.
"""
from typing import Protocol, List, Dict, Any, Optional

class BrokerBase(Protocol):
    def name(self) -> str: ...
    def fetch_ohlcv(self, symbol: str, timeframe: str, limit: int = 100) -> List[Dict[str, Any]]: ...
    def place_order(self, symbol: str, side: str, qty: float, price: Optional[float]=None, order_type: str="market") -> Dict[str, Any]: ...
    def cancel_order(self, order_id: str) -> bool: ...
    def get_balance(self) -> Dict[str, Any]: ...
    def get_positions(self) -> List[Dict[str, Any]]: ...
